// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"online-judge/biz/dal/mysql"
)

func init() {
	mysql.InitDB()
}

func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
